labels:
  - name: "add mod"
    conditions:
      - body: '\b- \[x\] Add mod to alternatives page\b'
  - name: "enhancement"
    conditions:
      - body: '\b- \[x\] Site changes\b'
  - name: "documentation"
    conditions:
      - body: '\b- \[x\] Chore/documentation updates\b'
  - name: "BREAKING CHANGE"
    conditions:
      - body: '^- \[x\] Tick this box if you made changes that may or may not break site functionality.$'
  - name: "Merge conflict identified"
    conditions:
      - mergeable: false
