name: Auto Label PRs, then add assignees and reviewers automatically.

run-name: PR management

on:
  pull_request_target:
    types: [opened, reopened, edited, synchronize]

jobs:
  add_labels_reviewers_assignees:
    name: Add labels, then reviewers & assignees
    runs-on: ubuntu-latest
    steps:
      - name: Auto-assign PR author as assignee
        if: github.event.action == 'opened'
        id: author-assignee
        uses: itsOliverBott/assign-pr-author-as-assignee@release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Label PR based on content
        id: label-pr
        uses: prulloac/configurable-pr-labeler@v1.1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Assign/unassign reviewers
        id: assign-reviewers
        uses: totallymoney/assign-reviewers-by-labels-action@v1.2.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          unassign-if-label-removed: true

      - name: Comment on PRs
        uses: dannyskoog/pull-request-comment@v1
        if: steps.assign-reviewers.outputs.assigned_status == 'success' && steps.assign_reviewers.outputs.unassigned_status == 'success'
        with:
          message: I've labeled your PR, assigned you and requested/un-requested reviews from the relevant people automatically. If you think I did it wrong, please comment below so one of our maintainers can double-check. Thanks!

      - name: Assigned/unassigned reviewers success debug log
        if: steps.assign-reviewers.outputs.assigned_status == 'success' && steps.assign_reviewers.outputs.unassigned_status == 'success'
        run: |
          echo "Successfully assigned/unassigned reviewers! Printing more info below..."
          echo "If values return null, that means I didn't do anything.\n"

          echo "PR I assigned reviewers to: ${{ steps.assign_reviewers.outputs.assigned_url }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "I assigned: ${{ steps.reviewer.outputs.assigned_reviewers }}"
          echo "Additional info: ${{ steps.assign_reviewers.outputs.assigned_message }}"

          echo "PR I unassigned reviewers to: ${{ steps.assign_reviewers.outputs.unassigned_url }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "I unassigned: ${{ steps.reviewer.outputs.unassigned_reviewers }}"
          echo "Additional info: ${{ steps.assign_reviewers.outputs.unassigned_message }}"

      - name: Assigned/unassigned reviewers failure(?) debug log
        if: steps.assign-reviewers.outputs.assigned_status == 'info' && steps.assign_reviewers.outputs.unassigned_status == 'info'
        run: |
          echo "Uh-oh! I ran into an issue when assigning/unassigning reviewers! Here's some info: \n"

          echo "PR I attempted to assign reviewers to: ${{ steps.assign_reviewers.outputs.assigned_url }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Info: ${{ steps.assign_reviewers.outputs.assigned_message }}"

          echo "PR I unassigned reviewers to: ${{ steps.assign_reviewers.outputs.unassigned_url }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Info: ${{ steps.assign_reviewers.outputs.unassigned_message }}"
