name: Update Crowdin strings bi-directionally

run-name: Update from Crowdin

on:
  schedule:
    - cron: "30 */3 * * *"
  push:
    branches-ignore:
      - i18n-crowdin-translations
      - manual-crowdin-updates
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  crowdin-translations-progress:
    name: Crowdin translations progress updater
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: "main"

      - name: Generate Crowdin translations progress markdown
        uses: benjaminjonard/crowdin-translations-progress-action@1.0.7
        with:
          languages_per_row: 10
          minimum_completion_percent: 80
          file: README.md # Maybe change later?
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: Push changes
        uses: actions-go/push@v1
        with:
          author-name: Actionsbot
          author-email: actions@github.com
          commit-message: "Update Crowdin translation progress badge"
          remote: origin
          remote-ref: main

  update-from-crowdin:
    name: Update strings from Crowdin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: "main"

      - name: Check last author
        id: check-author
        run: |
          LAST_COMMIT_AUTHOR=$(git log -1 --pretty=format:'%ae')
          echo "Last commit author: $LAST_COMMIT_AUTHOR"
          echo "::set-output name=author::$LAST_COMMIT_AUTHOR"

      - name: Grab strings from Crowdin
        if: steps.check-author.outputs.author != 'support+bot@crowdin.com' && steps.check-author.outputs.author != 'actions@github.com'
        uses: crowdin/github-action@v2.1.1
        with: # This part can be a little fragile, be careful!
          upload_sources: true
          upload_translations: false
          upload_language: en
          download_sources: false
          download_translations: true
          source: i18n/lang/en-US.json
          translation: i18n/lang/%locale%.json
          export_only_approved: true
          localization_branch_name: i18n-crowdin-translations
          create_pull_request: true
          pull_request_title: (Crowdin Action) New translation strings
          pull_request_body: New translated strings are now available!
          pull_request_labels: crowdin
          pull_request_base_branch_name: "main"
          github_user_name: Crowdin Bot (Actions)
          github_user_email: support+bot@crowdin.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
